config/routes.rb
Rails.application.routes.draw do
  devise_for :users :controllers => { :confirmations => 'devise/confirmations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: 'devise/sessions#new'
  end
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_like_counter

  private

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, foreign_key: :post_id
  has_many :comments, foreign_key: :post_id

  validates :title, presence: true, length: { maximum: 250 }
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comment_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def most_recent_comments
    comments.order(created_at: :desc).includes(:author).limit(5)
  end

  private

  def update_post_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'

  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    users_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :bio, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :bio, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new(user_id: @user.id, post_id: @post.id, text: params[:comment][:text])
    if @comment.save
      redirect_to user_post_comments_path(@post.author.id, @post.id)
    else
      render 'new'
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(user: @user, post: @post)

    if @like.save
      flash[:success] = 'You liked the post.'
    else
      flash.now[:error] = 'Error'
    end

    redirect_to user_posts_path(@post.author.id, @post.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: [:show]

  def index
    @posts = @user.posts.includes(:comments)
  end

  def show
    # The @post is already set by the `set_post` method
  end

  private

  def set_user
    @set_user ||= User.includes(:posts).find(params[:user_id])
  end

  def set_post
    @set_post ||= @user.posts.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.new(author_id: @user.id, title: params[:post][:title], text: params[:post][:text])
    if @post.save
      redirect_to user_posts_path(@post.author.id)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: [:index]
  before_action :set_user, only: [:show]

  def index
    # @users is already set by the `set_users` method
  end

  def show
    # @user is already set by the `set_user` method
  end

  private

  def set_users
    @set_users ||= User.includes(:posts).all
  end

  def set_user
    @set_user ||= User.includes(:posts).find(params[:id])
    @recent_posts = @set_user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment, url: user_post_comments_path(@post.author.id, @post.id) do |form| %>
    <div class="container col">
      <h3 class="new-comment-header">Add new comment</h3>
      <%= form.text_field :text, required: true, autofocus: true, placeholder: 'Add your comment here' %>
      <%= form.submit "Comment", class: "comment-button"%>
    <div>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts container">
<h1>Here is a list of posts for a given user</h1>
  <div class="user_item row">
    <div class="user_img">
      <img src=<%= @user.photo %> alt="user_img">
    </div>

    <div class="user_desc_cont">
      <div class="user_desc col">
        <h2 class="user_name"><%= link_to @user.name, user_path(@user) %></h2>
        <p class="user_post_number">Number of posts: <%= @user.posts_count %></p>  
      </div>
    </div> 
  </div>

  <ul class="post_list post_list_show col">
    <% @posts.each do |post| %>
      <li class="post_item_desc">

        <div class="post_item">
          <h4 class="post_title"><%= link_to post.title, user_post_path(@user, post) %></h4>
          <p class="post_text"><%= post.text %></p>
          <p class="comments_likes">
            Comments: <%= post.comments_count %>, 
            Likes: <%= post.likes_count %>
          </p>
        </div>

        <div class="post_comments">
          <% if post.recent_comments.length == 0 %>
            <p>No Comment</p>
          <% else %>
            <% post.recent_comments.each do |comment| %>
              <p class="comment"><%= comment.user.name %>: <%= comment.text %></p>
            <% end %>
          <% end %>
        </div>

      </li>
    <% end %>
  </ul>

  <div class="btn_cont">
    <button class="btn"><%= link_to 'Add new post', new_user_post_path(@user) %></button>
  </div>

</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path(@user.id) do |form| %>
    <div class="container col">
      <h2 class="new_post_header">Add new post</h2>
      <%= form.label :title, class: "form-label" do %>
        Title:
        <%= form.text_field :title, required: true, autofocus: true, class: "title-input", placeholder: 'Add your title here' %>
      <% end %>
      <%= form.label :text, class: "text-label" do %>
        Text:
        <%= form.text_area :text, required: true, autofocus: true, class: "text-input", placeholder: 'Add your text here' %>
      <% end %>
      <%= form.submit "Create", class: "create-button" %>
    </div>
  <% end %>
  

app/views/posts/show.html.erb
<div class="post_desc container">
<h1>Here is a specific post for a given user</h1>
  <div class="post_detail">
    <div class="post_header">
      <h4 class="post_title"><%= @post.title %> by <%= @post.author.name %></h4>
      <p class="comments_likes">
        Comments: <%= @post.comments_count %>, 
        Likes: <%= @post.likes_count %>
      </p>
    </div>

    <div class="post_body">
      <p><%= @post.text %></p>
    </div>
  </div>

  <div class="comment-like-button">
    <%= form_with model: @like, url: user_post_likes_path(@post.author, @post), scope: :like do |form|%>
      <%= form.submit 'Like', class: 'single-button' %>
    <% end %>
    <button type="button" class="single-button">
      <%= link_to "Comment", new_user_post_comment_path(post_id: @post.id), { class: "user-link" } %>
    </button>
  </div>

  <div class="post_comments">
    <ul class="post_comments_list">
      <% if @post.comments.length == 0 %>
        <li class="post_comments_item">
          <p class="comment">No comment</p>
        </li>
      <% else %>
        <% @post.comments.each do |comment| %>
          <li class="post_comments_item">
            <p class="comment"><%= comment.user.name %>: <%= comment.text %></p>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>

</div>

app/views/users/index.html.erb
<div class="users container">
<h1>Here is a list of users</h1>
  <ul class="user_list col">
    <% @users.each do |user| %>

      <li class="user_item row">
        <div class="user_img">
          <img src=<%= user.photo %> alt="user_img">
        </div>
        
        <div class="user_desc_cont">
            <div class="user_desc col">
              <h2 class="user_name">
                <%= link_to user.name, user_path(user) %>
              </h2>
              <p class="user_post_number">Number of posts: <%= user.posts_count %></p>  
            </div>
        </div> 
       
      </li>
      
    <% end %>
  </ul>

</div>

app/views/users/show.html.erb
<div class="user_show container">
<h1>Here is a specific user</h1>
  <div class="user_item row">
    <div class="user_img">
      <img src=<%= @user.photo %> alt="user_img">
    </div>

    <div class="user_desc_cont">
      <div class="user_desc col">
        <h2 class="user_name">
          <%= link_to @user.name, user_path(@user) %>
        </h2>
        <p class="user_post_number">Number of posts: <%= @user.posts_count %></p>  
      </div>
    </div> 
  </div>

  <div class="user_bio">
    <p class="show_title">Bio</p>
    <p class="bio_detail"><%= @user.bio %></p>
  </div>

  <ul class="post_list col">
    <% @recent_posts.each do |post| %>
      <li class="post_item">
        <h4 class="post_title"><%= link_to post.title, user_post_path(@user, post) %></h4>
        <p class="post_text"><%= post.text %></p>
        <p class="comments_likes">
          Comments: <%= post.comments_count %>,
          Likes: <%= post.likes_count %>
        </p>
      </li>
    <% end %>
  </ul>

  <div class="btn_cont">
    <button class="btn"><%= link_to 'See all posts', user_posts_path(@user) %></button>
  </div>
</div>